name: Pipeline

on:
  push:
    branches: ['*']
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main, next]

jobs:
  linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Download deps
        uses: docker/build-push-action@v2
        with:
          tags: ci
          push: false
          load: true
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}, mode=max
        
      - name: Debug
        run: |
          docker run --network none --env GOPATH="" -d --name test --workdir /go/work -v $PWD:/go/work ci sh
          docker inspect test

      # Disable network so that Azure specific behavior (GH Actions runs in Azure) doesn't happen
      - name: Quality
        run: docker run --network none --env GOPATH="" --rm --workdir /go/work -v $PWD:/go/work ci make quality

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1

      # - name: Build and test plugin
      #   run: docker run --network none --env GOPATH="" --rm -v $PWD:/go/work ci make e2e
  # mac:
  #   strategy:
  #     fail-fast: false
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.16

  #     - name: Quality checks
  #       run: make quality

  #     - name: Build and test plugin
  #       run: make e2e